- hosts: webserver
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  become: yes

  tasks:
    - name: install apache2 on remote server
      apt:
        name: apache2
        state: latest
        update_cache: yes

    - name: make sure apache2 is running
      service:
            name: apache2
            state: started
            enabled: true
